STP: Remove an unused variable.
Fix

```
epan/dissectors/packet-bpdu.c:327:36: error: variable 'msti' set but not used [-Werror,-Wunused-but-set-variable]
  int   total_msti_length, offset, msti, msti_format;
                                   ^
```