CMake: Work around Homebrew's broken pkg-config.
Homebrew configures pkg-config with
"--with-system-include-path=/Library/Developer/CommandLineTools/SDKs/<sdk>/usr":
https://github.com/Homebrew/homebrew-core/blob/e2c833d326c45d9aaf4e26af6dd8b2f31564dc04/Formula/pkg-config.rb#L49

(On my system here, <sdk> is MacOSX10.15.sdk.)

CMake in turn passes "--variable=includedir" to pkg-config:
https://gitlab.kitware.com/cmake/cmake/-/blob/df4ed1e9/Modules/UsePkgConfig.cmake#L43

As a result, we end up finding the Libxml2 and zlib includes in
Homebrew's specified prefix. (The mismatched INCLUDE_DIR/_LIBRARY
prefixes look odd, but may not have anything to do with the issue at
hand.)

```
ag --nonumbers '^(libxml2|zlib)_(include_dir|library):' CMakeCache.txt
LIBXML2_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2
LIBXML2_LIBRARY:FILEPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/lib/libxml2.tbd
ZLIB_INCLUDE_DIR:PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include
ZLIB_LIBRARY:FILEPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk/usr/lib/libz.tbd
```

On my system here, stdio.h under Homebrew's prefix has nullability
issues:

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:93:16: error: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Werror,-Wnullability-completeness]
        unsigned char   *_base;
                        ^
```

If CMAKE_OSX_SYSROOT is defined and exists, make sure we search it first
for Libxml2 and zlib headers and libraries so that we bypass Homebrew.
Fixes #16868.